// Mocks generated by Mockito 5.4.6 from annotations
// in websocket_service/test/stores/websocket_preferences_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:constants/stores/error/error_store.dart' as _i7;
import 'package:mobx/mobx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:websocket_service/domain/repository/websocket_preferences_repository.dart'
    as _i4;
import 'package:websocket_service/models/websocket_channel_config.dart' as _i6;
import 'package:websocket_service/models/websocket_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWebSocketPreferences_0 extends _i1.SmartFake
    implements _i2.WebSocketPreferences {
  _FakeWebSocketPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_1 extends _i1.SmartFake
    implements _i3.ReactiveContext {
  _FakeReactiveContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WebSocketPreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketPreferencesRepository extends _i1.Mock
    implements _i4.WebSocketPreferencesRepository {
  MockWebSocketPreferencesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.WebSocketPreferences> get preferencesStream =>
      (super.noSuchMethod(
        Invocation.getter(#preferencesStream),
        returnValue: _i5.Stream<_i2.WebSocketPreferences>.empty(),
      ) as _i5.Stream<_i2.WebSocketPreferences>);

  @override
  _i5.Future<_i2.WebSocketPreferences> getPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue: _i5.Future<_i2.WebSocketPreferences>.value(
            _FakeWebSocketPreferences_0(
          this,
          Invocation.method(
            #getPreferences,
            [],
          ),
        )),
      ) as _i5.Future<_i2.WebSocketPreferences>);

  @override
  _i5.Future<void> savePreferences(_i2.WebSocketPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferences,
          [preferences],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i6.WebSocketChannelConfig> getAvailableChannels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableChannels,
          [],
        ),
        returnValue: <_i6.WebSocketChannelConfig>[],
      ) as List<_i6.WebSocketChannelConfig>);

  @override
  _i5.Future<void> setChannelEnabled(
    String? channelId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChannelEnabled,
          [
            channelId,
            enabled,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setChannelPriority(
    String? channelId,
    _i2.NotificationPriority? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChannelPriority,
          [
            channelId,
            priority,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRealTimeUpdatesEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRealTimeUpdatesEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setConnectionStatusEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConnectionStatusEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Set<String> getSubscribedChannels() => (super.noSuchMethod(
        Invocation.method(
          #getSubscribedChannels,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  bool shouldShowNotification(
    String? channelId,
    _i2.NotificationPriority? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldShowNotification,
          [
            channelId,
            priority,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ErrorStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorStore extends _i1.Mock implements _i7.ErrorStore {
  MockErrorStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as String);

  @override
  set errorMessage(String? value) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.ReactiveContext);

  @override
  void setErrorMessage(String? message) => super.noSuchMethod(
        Invocation.method(
          #setErrorMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset(String? value) => super.noSuchMethod(
        Invocation.method(
          #reset,
          [value],
        ),
        returnValueForMissingStub: null,
      );
}
