outputDir: "./lib/Data/Services/api"
inputSpec: api-docs.yaml  # Swagger/OpenAPI spec file
generatorName: dart
globalProperties:
  generateGitIgnoreFile: false
additionalProperties:
  pubName: "api_client"
  pubVersion: "0.0.2"
  sortParamsByRequiredFlag: true
  ensureUniqueParams: true
  nullableFields: true  # Thêm option này
  useNullSafetySyntax: true  # Thêm option này
  useEnumExtension: true
  dateLibrary: time_machine
  skipNullSafety: true
  pubSpecVersion: "^3.6.0"