require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << '.'
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end

desc 'Run all tests'
task default: :test

desc 'Run unit tests only'
Rake::TestTask.new(:unit) do |t|
  t.libs << 'test'
  t.libs << '.'
  t.test_files = FileList['test/version_manager_test.rb', 'test/version_history_manager_test.rb']
  t.verbose = true
end

desc 'Run integration tests only'
Rake::TestTask.new(:integration) do |t|
  t.libs << 'test'
  t.libs << '.'
  t.test_files = FileList['test/integration_test.rb']
  t.verbose = true
end

desc 'Generate test coverage report'
task :coverage do
  ENV['COVERAGE'] = 'true'
  Rake::Task[:test].invoke
end

desc 'Clean test artifacts'
task :clean do
  FileUtils.rm_rf('test/reports')
  FileUtils.rm_rf('coverage')
end