// Mocks generated by Mockito 5.4.6 from annotations
// in data/test/websocket/services/message_queue_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:data/websocket/interfaces/i_websocket_data_synchronizer.dart'
    as _i3;
import 'package:data/websocket/models/sync_operation.dart' as _i2;
import 'package:data/websocket/models/websocket_message.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IWebSocketDataSynchronizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWebSocketDataSynchronizer extends _i1.Mock
    implements _i3.IWebSocketDataSynchronizer {
  MockIWebSocketDataSynchronizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.SyncResult> get syncResultStream => (super.noSuchMethod(
        Invocation.getter(#syncResultStream),
        returnValue: _i4.Stream<_i2.SyncResult>.empty(),
      ) as _i4.Stream<_i2.SyncResult>);

  @override
  _i4.Stream<_i2.DataConflict> get conflictStream => (super.noSuchMethod(
        Invocation.getter(#conflictStream),
        returnValue: _i4.Stream<_i2.DataConflict>.empty(),
      ) as _i4.Stream<_i2.DataConflict>);

  @override
  _i4.Future<_i2.SyncResult> processMessage(_i5.WebSocketMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #processMessage,
          [message],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #processMessage,
            [message],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<List<_i2.SyncResult>> processBatch(
          List<_i5.WebSocketMessage>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #processBatch,
          [messages],
        ),
        returnValue: _i4.Future<List<_i2.SyncResult>>.value(<_i2.SyncResult>[]),
      ) as _i4.Future<List<_i2.SyncResult>>);

  @override
  _i4.Future<_i2.SyncResult> resolveConflict(
    _i2.DataConflict? conflict,
    String? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            conflict,
            strategy,
          ],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #resolveConflict,
            [
              conflict,
              strategy,
            ],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<List<_i2.SyncOperation>> getPendingOperations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingOperations,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.SyncOperation>>.value(<_i2.SyncOperation>[]),
      ) as _i4.Future<List<_i2.SyncOperation>>);

  @override
  _i4.Future<void> clearCompletedOperations() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedOperations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
