// Mocks generated by Mockito 5.4.6 from annotations
// in data/test/websocket/services/offline_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:data/websocket/interfaces/i_message_queue_service.dart' as _i5;
import 'package:data/websocket/interfaces/i_websocket_data_synchronizer.dart'
    as _i9;
import 'package:data/websocket/models/queued_message.dart' as _i2;
import 'package:data/websocket/models/sync_operation.dart' as _i3;
import 'package:data/websocket/models/websocket_message.dart' as _i7;
import 'package:data/websocket/services/missed_update_synchronizer.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageQueueConfig_0 extends _i1.SmartFake
    implements _i2.MessageQueueConfig {
  _FakeMessageQueueConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageQueueStats_1 extends _i1.SmartFake
    implements _i2.MessageQueueStats {
  _FakeMessageQueueStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueueProcessingResult_2 extends _i1.SmartFake
    implements _i2.QueueProcessingResult {
  _FakeQueueProcessingResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_3 extends _i1.SmartFake implements _i3.SyncResult {
  _FakeSyncResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSynchronizationResult_4 extends _i1.SmartFake
    implements _i4.SynchronizationResult {
  _FakeSynchronizationResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IMessageQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessageQueueService extends _i1.Mock
    implements _i5.IMessageQueueService {
  MockIMessageQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i2.QueueProcessingResult> get processingResults =>
      (super.noSuchMethod(
        Invocation.getter(#processingResults),
        returnValue: _i6.Stream<_i2.QueueProcessingResult>.empty(),
      ) as _i6.Stream<_i2.QueueProcessingResult>);

  @override
  _i6.Stream<_i2.MessageQueueStats> get queueStats => (super.noSuchMethod(
        Invocation.getter(#queueStats),
        returnValue: _i6.Stream<_i2.MessageQueueStats>.empty(),
      ) as _i6.Stream<_i2.MessageQueueStats>);

  @override
  bool get isProcessing => (super.noSuchMethod(
        Invocation.getter(#isProcessing),
        returnValue: false,
      ) as bool);

  @override
  _i2.MessageQueueConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeMessageQueueConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.MessageQueueConfig);

  @override
  _i2.MessageQueueStats get stats => (super.noSuchMethod(
        Invocation.getter(#stats),
        returnValue: _FakeMessageQueueStats_1(
          this,
          Invocation.getter(#stats),
        ),
      ) as _i2.MessageQueueStats);

  @override
  _i6.Future<String> queueMessage(
    _i7.WebSocketMessage? message, {
    _i2.QueuedMessagePriority? priority = _i2.QueuedMessagePriority.normal,
    DateTime? expiresAt,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueMessage,
          [message],
          {
            #priority: priority,
            #expiresAt: expiresAt,
            #metadata: metadata,
          },
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #queueMessage,
            [message],
            {
              #priority: priority,
              #expiresAt: expiresAt,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<String>> queueBatch(
    List<_i7.WebSocketMessage>? messages, {
    _i2.QueuedMessagePriority? priority = _i2.QueuedMessagePriority.normal,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueBatch,
          [messages],
          {
            #priority: priority,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Stream<_i2.QueueProcessingResult> startProcessing({int? batchSize}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startProcessing,
          [],
          {#batchSize: batchSize},
        ),
        returnValue: _i6.Stream<_i2.QueueProcessingResult>.empty(),
      ) as _i6.Stream<_i2.QueueProcessingResult>);

  @override
  _i6.Future<void> stopProcessing() => (super.noSuchMethod(
        Invocation.method(
          #stopProcessing,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.QueueProcessingResult> processMessage(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #processMessage,
          [messageId],
        ),
        returnValue: _i6.Future<_i2.QueueProcessingResult>.value(
            _FakeQueueProcessingResult_2(
          this,
          Invocation.method(
            #processMessage,
            [messageId],
          ),
        )),
      ) as _i6.Future<_i2.QueueProcessingResult>);

  @override
  _i6.Future<List<_i2.QueuedMessage>> getQueuedMessages({
    _i2.QueuedMessageStatus? status,
    _i2.QueuedMessagePriority? priority,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuedMessages,
          [],
          {
            #status: status,
            #priority: priority,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<List<_i2.QueuedMessage>>.value(<_i2.QueuedMessage>[]),
      ) as _i6.Future<List<_i2.QueuedMessage>>);

  @override
  _i6.Future<_i2.QueuedMessage?> getQueuedMessage(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuedMessage,
          [messageId],
        ),
        returnValue: _i6.Future<_i2.QueuedMessage?>.value(),
      ) as _i6.Future<_i2.QueuedMessage?>);

  @override
  _i6.Future<bool> removeMessage(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #removeMessage,
          [messageId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> clearMessages({_i2.QueuedMessageStatus? status}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearMessages,
          [],
          {#status: status},
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> clearExpiredMessages() => (super.noSuchMethod(
        Invocation.method(
          #clearExpiredMessages,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> updateConfig(_i2.MessageQueueConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [config],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getQueueSize() => (super.noSuchMethod(
        Invocation.method(
          #getQueueSize,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> isQueueFull() => (super.noSuchMethod(
        Invocation.method(
          #isQueueFull,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> retryFailedMessages({int? maxRetries}) => (super.noSuchMethod(
        Invocation.method(
          #retryFailedMessages,
          [],
          {#maxRetries: maxRetries},
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> prioritizeMessage(
    String? messageId,
    _i2.QueuedMessagePriority? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #prioritizeMessage,
          [
            messageId,
            priority,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> getQueueHealth() => (super.noSuchMethod(
        Invocation.method(
          #getQueueHealth,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IWebSocketDataSynchronizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWebSocketDataSynchronizer extends _i1.Mock
    implements _i9.IWebSocketDataSynchronizer {
  MockIWebSocketDataSynchronizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.SyncResult> get syncResultStream => (super.noSuchMethod(
        Invocation.getter(#syncResultStream),
        returnValue: _i6.Stream<_i3.SyncResult>.empty(),
      ) as _i6.Stream<_i3.SyncResult>);

  @override
  _i6.Stream<_i3.DataConflict> get conflictStream => (super.noSuchMethod(
        Invocation.getter(#conflictStream),
        returnValue: _i6.Stream<_i3.DataConflict>.empty(),
      ) as _i6.Stream<_i3.DataConflict>);

  @override
  _i6.Future<_i3.SyncResult> processMessage(_i7.WebSocketMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #processMessage,
          [message],
        ),
        returnValue: _i6.Future<_i3.SyncResult>.value(_FakeSyncResult_3(
          this,
          Invocation.method(
            #processMessage,
            [message],
          ),
        )),
      ) as _i6.Future<_i3.SyncResult>);

  @override
  _i6.Future<List<_i3.SyncResult>> processBatch(
          List<_i7.WebSocketMessage>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #processBatch,
          [messages],
        ),
        returnValue: _i6.Future<List<_i3.SyncResult>>.value(<_i3.SyncResult>[]),
      ) as _i6.Future<List<_i3.SyncResult>>);

  @override
  _i6.Future<_i3.SyncResult> resolveConflict(
    _i3.DataConflict? conflict,
    String? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            conflict,
            strategy,
          ],
        ),
        returnValue: _i6.Future<_i3.SyncResult>.value(_FakeSyncResult_3(
          this,
          Invocation.method(
            #resolveConflict,
            [
              conflict,
              strategy,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SyncResult>);

  @override
  _i6.Future<List<_i3.SyncOperation>> getPendingOperations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingOperations,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.SyncOperation>>.value(<_i3.SyncOperation>[]),
      ) as _i6.Future<List<_i3.SyncOperation>>);

  @override
  _i6.Future<void> clearCompletedOperations() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedOperations,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MissedUpdateSynchronizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockMissedUpdateSynchronizer extends _i1.Mock
    implements _i4.MissedUpdateSynchronizer {
  MockMissedUpdateSynchronizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i4.SynchronizationEvent> get synchronizationEvents =>
      (super.noSuchMethod(
        Invocation.getter(#synchronizationEvents),
        returnValue: _i6.Stream<_i4.SynchronizationEvent>.empty(),
      ) as _i6.Stream<_i4.SynchronizationEvent>);

  @override
  bool get isSynchronizing => (super.noSuchMethod(
        Invocation.getter(#isSynchronizing),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i4.SynchronizationResult> synchronizeMissedUpdates({
    required DateTime? backgroundTime,
    required DateTime? resumeTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #synchronizeMissedUpdates,
          [],
          {
            #backgroundTime: backgroundTime,
            #resumeTime: resumeTime,
          },
        ),
        returnValue: _i6.Future<_i4.SynchronizationResult>.value(
            _FakeSynchronizationResult_4(
          this,
          Invocation.method(
            #synchronizeMissedUpdates,
            [],
            {
              #backgroundTime: backgroundTime,
              #resumeTime: resumeTime,
            },
          ),
        )),
      ) as _i6.Future<_i4.SynchronizationResult>);

  @override
  _i6.Future<_i4.SynchronizationResult> performFullDataRefresh() =>
      (super.noSuchMethod(
        Invocation.method(
          #performFullDataRefresh,
          [],
        ),
        returnValue: _i6.Future<_i4.SynchronizationResult>.value(
            _FakeSynchronizationResult_4(
          this,
          Invocation.method(
            #performFullDataRefresh,
            [],
          ),
        )),
      ) as _i6.Future<_i4.SynchronizationResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
