// Mocks generated by Mockito 5.4.6 from annotations
// in data/test/websocket/services/websocket_data_synchronizer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:data/websocket/database/sync_database.dart' as _i3;
import 'package:data/websocket/interfaces/i_conflict_resolver.dart' as _i10;
import 'package:data/websocket/interfaces/i_message_router.dart' as _i7;
import 'package:data/websocket/models/sync_operation.dart' as _i11;
import 'package:data/websocket/models/websocket_message.dart' as _i9;
import 'package:data/websocket/models/websocket_message_type.dart' as _i8;
import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CustomersTable_1 extends _i1.SmartFake
    implements _i3.$CustomersTable {
  _Fake$CustomersTable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$InventoryTable_2 extends _i1.SmartFake
    implements _i3.$InventoryTable {
  _Fake$InventoryTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$OrdersTable_3 extends _i1.SmartFake implements _i3.$OrdersTable {
  _Fake$OrdersTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SyncOperationEntriesTable_4 extends _i1.SmartFake
    implements _i3.$SyncOperationEntriesTable {
  _Fake$SyncOperationEntriesTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$QueuedMessageEntriesTable_5 extends _i1.SmartFake
    implements _i3.$QueuedMessageEntriesTable {
  _Fake$QueuedMessageEntriesTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SyncDatabaseManager_6 extends _i1.SmartFake
    implements _i3.$SyncDatabaseManager {
  _Fake$SyncDatabaseManager_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_7 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_8 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_9 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_10 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_11 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_12 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_13 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_14 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_15<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_16<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_17<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_18<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_19<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_20<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_21<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_22<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_23 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncDatabase extends _i1.Mock implements _i3.SyncDatabase {
  MockSyncDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i2.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_0(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i2.MigrationStrategy);

  @override
  _i3.$CustomersTable get customers => (super.noSuchMethod(
        Invocation.getter(#customers),
        returnValue: _Fake$CustomersTable_1(
          this,
          Invocation.getter(#customers),
        ),
      ) as _i3.$CustomersTable);

  @override
  _i3.$InventoryTable get inventory => (super.noSuchMethod(
        Invocation.getter(#inventory),
        returnValue: _Fake$InventoryTable_2(
          this,
          Invocation.getter(#inventory),
        ),
      ) as _i3.$InventoryTable);

  @override
  _i3.$OrdersTable get orders => (super.noSuchMethod(
        Invocation.getter(#orders),
        returnValue: _Fake$OrdersTable_3(
          this,
          Invocation.getter(#orders),
        ),
      ) as _i3.$OrdersTable);

  @override
  _i3.$SyncOperationEntriesTable get syncOperationEntries =>
      (super.noSuchMethod(
        Invocation.getter(#syncOperationEntries),
        returnValue: _Fake$SyncOperationEntriesTable_4(
          this,
          Invocation.getter(#syncOperationEntries),
        ),
      ) as _i3.$SyncOperationEntriesTable);

  @override
  _i3.$QueuedMessageEntriesTable get queuedMessageEntries =>
      (super.noSuchMethod(
        Invocation.getter(#queuedMessageEntries),
        returnValue: _Fake$QueuedMessageEntriesTable_5(
          this,
          Invocation.getter(#queuedMessageEntries),
        ),
      ) as _i3.$QueuedMessageEntriesTable);

  @override
  _i3.$SyncDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$SyncDatabaseManager_6(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i3.$SyncDatabaseManager);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
      ) as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i2.DatabaseSchemaEntity>[],
      ) as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_7(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_8(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_9(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_10(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i6.dummyValue<_i2.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_11(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_12(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_13(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<List<_i3.Customer>> getAllCustomers() => (super.noSuchMethod(
        Invocation.method(
          #getAllCustomers,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
      ) as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<_i3.Customer?> getCustomerByExternalId(String? externalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomerByExternalId,
          [externalId],
        ),
        returnValue: _i5.Future<_i3.Customer?>.value(),
      ) as _i5.Future<_i3.Customer?>);

  @override
  _i5.Future<int> insertCustomer(_i3.CustomersCompanion? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCustomer,
          [customer],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateCustomer(
    String? externalId,
    _i3.CustomersCompanion? customer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomer,
          [
            externalId,
            customer,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteCustomer(String? externalId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomer,
          [externalId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.InventoryData>> getAllInventory() => (super.noSuchMethod(
        Invocation.method(
          #getAllInventory,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.InventoryData>>.value(<_i3.InventoryData>[]),
      ) as _i5.Future<List<_i3.InventoryData>>);

  @override
  _i5.Future<_i3.InventoryData?> getInventoryByExternalId(String? externalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInventoryByExternalId,
          [externalId],
        ),
        returnValue: _i5.Future<_i3.InventoryData?>.value(),
      ) as _i5.Future<_i3.InventoryData?>);

  @override
  _i5.Future<int> insertInventory(_i3.InventoryCompanion? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertInventory,
          [item],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateInventory(
    String? externalId,
    _i3.InventoryCompanion? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInventory,
          [
            externalId,
            item,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteInventory(String? externalId) => (super.noSuchMethod(
        Invocation.method(
          #deleteInventory,
          [externalId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Order>> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i5.Future<List<_i3.Order>>);

  @override
  _i5.Future<_i3.Order?> getOrderByExternalId(String? externalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderByExternalId,
          [externalId],
        ),
        returnValue: _i5.Future<_i3.Order?>.value(),
      ) as _i5.Future<_i3.Order?>);

  @override
  _i5.Future<int> insertOrder(_i3.OrdersCompanion? order) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrder,
          [order],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateOrder(
    String? externalId,
    _i3.OrdersCompanion? order,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [
            externalId,
            order,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteOrder(String? externalId) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [externalId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.SyncOperationEntry>> getPendingSyncOperations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncOperations,
          [],
        ),
        returnValue: _i5.Future<List<_i3.SyncOperationEntry>>.value(
            <_i3.SyncOperationEntry>[]),
      ) as _i5.Future<List<_i3.SyncOperationEntry>>);

  @override
  _i5.Future<int> insertSyncOperation(
          _i3.SyncOperationEntriesCompanion? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSyncOperation,
          [operation],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateSyncOperationStatus(
    String? operationId,
    String? status, {
    String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSyncOperationStatus,
          [
            operationId,
            status,
          ],
          {#error: error},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> clearCompletedSyncOperations() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedSyncOperations,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueuedMessageEntry>> getAllQueuedMessages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllQueuedMessages,
          [],
        ),
        returnValue: _i5.Future<List<_i3.QueuedMessageEntry>>.value(
            <_i3.QueuedMessageEntry>[]),
      ) as _i5.Future<List<_i3.QueuedMessageEntry>>);

  @override
  _i5.Future<List<_i3.QueuedMessageEntry>> getQueuedMessagesByStatus(
          String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuedMessagesByStatus,
          [status],
        ),
        returnValue: _i5.Future<List<_i3.QueuedMessageEntry>>.value(
            <_i3.QueuedMessageEntry>[]),
      ) as _i5.Future<List<_i3.QueuedMessageEntry>>);

  @override
  _i5.Future<List<_i3.QueuedMessageEntry>> getQueuedMessagesByPriority(
          String? priority) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuedMessagesByPriority,
          [priority],
        ),
        returnValue: _i5.Future<List<_i3.QueuedMessageEntry>>.value(
            <_i3.QueuedMessageEntry>[]),
      ) as _i5.Future<List<_i3.QueuedMessageEntry>>);

  @override
  _i5.Future<List<_i3.QueuedMessageEntry>> getPendingQueuedMessages(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingQueuedMessages,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.QueuedMessageEntry>>.value(
            <_i3.QueuedMessageEntry>[]),
      ) as _i5.Future<List<_i3.QueuedMessageEntry>>);

  @override
  _i5.Future<_i3.QueuedMessageEntry?> getQueuedMessageById(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuedMessageById,
          [messageId],
        ),
        returnValue: _i5.Future<_i3.QueuedMessageEntry?>.value(),
      ) as _i5.Future<_i3.QueuedMessageEntry?>);

  @override
  _i5.Future<int> insertQueuedMessage(
          _i3.QueuedMessageEntriesCompanion? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertQueuedMessage,
          [message],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateQueuedMessageStatus(
    String? messageId,
    String? status, {
    String? error,
    DateTime? processedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueuedMessageStatus,
          [
            messageId,
            status,
          ],
          {
            #error: error,
            #processedAt: processedAt,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateQueuedMessagePriority(
    String? messageId,
    String? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueuedMessagePriority,
          [
            messageId,
            priority,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> incrementRetryCount(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementRetryCount,
          [messageId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteQueuedMessage(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #deleteQueuedMessage,
          [messageId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearQueuedMessagesByStatus(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearQueuedMessagesByStatus,
          [status],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearExpiredQueuedMessages() => (super.noSuchMethod(
        Invocation.method(
          #clearExpiredQueuedMessages,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getQueuedMessageCount({String? status}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuedMessageCount,
          [],
          {#status: status},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueuedMessageEntry>> getFailedQueuedMessages(
          {int? maxRetries}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFailedQueuedMessages,
          [],
          {#maxRetries: maxRetries},
        ),
        returnValue: _i5.Future<List<_i3.QueuedMessageEntry>>.value(
            <_i3.QueuedMessageEntry>[]),
      ) as _i5.Future<List<_i3.QueuedMessageEntry>>);

  @override
  _i2.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_14(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(
    _i2.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates(
          [_i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_15<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
          _i2.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_16<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
          _i2.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_17<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_18<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_19<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
          Iterable<_i2.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_20<_i2.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
          _i2.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_21<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
      ) as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_22<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_22<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_15<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_15<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_15<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_23(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_23(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [IMessageRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessageRouter extends _i1.Mock implements _i7.IMessageRouter {
  MockIMessageRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void registerHandler(
    _i8.WebSocketMessageType? type,
    _i7.MessageHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #registerHandler,
          [
            type,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterHandler(_i8.WebSocketMessageType? type) => super.noSuchMethod(
        Invocation.method(
          #unregisterHandler,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> routeMessage(_i9.WebSocketMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #routeMessage,
          [message],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Set<_i8.WebSocketMessageType> getRegisteredTypes() => (super.noSuchMethod(
        Invocation.method(
          #getRegisteredTypes,
          [],
        ),
        returnValue: <_i8.WebSocketMessageType>{},
      ) as Set<_i8.WebSocketMessageType>);

  @override
  bool hasHandler(_i8.WebSocketMessageType? type) => (super.noSuchMethod(
        Invocation.method(
          #hasHandler,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearHandlers() => super.noSuchMethod(
        Invocation.method(
          #clearHandlers,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IConflictResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConflictResolver extends _i1.Mock implements _i10.IConflictResolver {
  MockIConflictResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> resolveConflict(
    _i11.DataConflict? conflict,
    _i10.ConflictResolutionStrategy? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            conflict,
            strategy,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i10.ConflictResolutionStrategy getDefaultStrategy(String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultStrategy,
          [entityType],
        ),
        returnValue: _i10.ConflictResolutionStrategy.useRemote,
      ) as _i10.ConflictResolutionStrategy);

  @override
  void setDefaultStrategy(
    String? entityType,
    _i10.ConflictResolutionStrategy? strategy,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setDefaultStrategy,
          [
            entityType,
            strategy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool canAutoResolve(_i11.DataConflict? conflict) => (super.noSuchMethod(
        Invocation.method(
          #canAutoResolve,
          [conflict],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, _i10.ConflictResolutionStrategy> getFieldMergeRules(
          String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFieldMergeRules,
          [entityType],
        ),
        returnValue: <String, _i10.ConflictResolutionStrategy>{},
      ) as Map<String, _i10.ConflictResolutionStrategy>);

  @override
  void setFieldMergeRules(
    String? entityType,
    Map<String, _i10.ConflictResolutionStrategy>? rules,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setFieldMergeRules,
          [
            entityType,
            rules,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
