// Mocks generated by Mockito 5.4.6 from annotations
// in data/test/websocket/stores/websocket_store_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:data/websocket/interfaces/i_websocket_service.dart' as _i2;
import 'package:data/websocket/models/websocket_connection_state.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IWebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWebSocketService extends _i1.Mock implements _i2.IWebSocketService {
  MockIWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.WebSocketConnectionState> get connectionState =>
      (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i3.Stream<_i4.WebSocketConnectionState>.empty(),
      ) as _i3.Stream<_i4.WebSocketConnectionState>);

  @override
  _i4.WebSocketConnectionState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i4.WebSocketConnectionState.disconnected,
      ) as _i4.WebSocketConnectionState);

  @override
  _i3.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void subscribe(
    String? channel,
    dynamic Function(dynamic)? callback,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [
            channel,
            callback,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe(String? channel) => super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [channel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> handleAppLifecycle(_i5.AppLifecycleState? state) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleAppLifecycle,
          [state],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
