name: core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.1.1
  drift: ^2.23.0
  drift_flutter: ^0.2.4
  freezed: ^2.5.7
  socket_io_client: ^3.0.2 
  validators: ^3.0.0
  get_it: ^8.0.3
  flutter_modular: ^6.3.4
  go_router: ^14.8.0
  data:
    path: ../data
  constants:
    path: ../constants
  app_drawer:
    path: ../app_drawer
  setting:
    path: ../setting

  flutter:
    sdk: flutter

dev_dependencies:
  drift_dev: ^2.23.0
  mobx_codegen: ^2.2.0