// Mocks generated by Mockito 5.4.6 from annotations
// in mix_fit/test/integration/error_system_migration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:core/error/models/api_error.dart' as _i8;
import 'package:core/error/models/app_error.dart' as _i7;
import 'package:core/error/models/client_error.dart' as _i11;
import 'package:core/error/models/network_error.dart' as _i10;
import 'package:core/error/models/network_status.dart' as _i13;
import 'package:core/error/models/validation_error.dart' as _i9;
import 'package:core/error/services/error_service_interface.dart' as _i5;
import 'package:core/error/stores/error_store.dart' as _i12;
import 'package:customer_management/domain/entities/customer.dart' as _i15;
import 'package:customer_management/domain/usecases/validate_customer_fields_usecase.dart'
    as _i3;
import 'package:mobx/mobx.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:websocket_service/domain/repository/websocket_preferences_repository.dart'
    as _i16;
import 'package:websocket_service/models/websocket_channel_config.dart' as _i17;
import 'package:websocket_service/models/websocket_preferences.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeObservableList_0<T> extends _i1.SmartFake
    implements _i2.ObservableList<T> {
  _FakeObservableList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_2 extends _i1.SmartFake
    implements _i2.ReactiveContext {
  _FakeReactiveContext_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFieldValidationResult_3 extends _i1.SmartFake
    implements _i3.FieldValidationResult {
  _FakeFieldValidationResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebSocketPreferences_4 extends _i1.SmartFake
    implements _i4.WebSocketPreferences {
  _FakeWebSocketPreferences_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IErrorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIErrorService extends _i1.Mock implements _i5.IErrorService {
  MockIErrorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i7.AppError>> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i6.Stream<List<_i7.AppError>>.empty(),
      ) as _i6.Stream<List<_i7.AppError>>);

  @override
  _i6.Stream<_i7.AppError?> get currentErrorStream => (super.noSuchMethod(
        Invocation.getter(#currentErrorStream),
        returnValue: _i6.Stream<_i7.AppError?>.empty(),
      ) as _i6.Stream<_i7.AppError?>);

  @override
  bool get hasErrors => (super.noSuchMethod(
        Invocation.getter(#hasErrors),
        returnValue: false,
      ) as bool);

  @override
  List<_i7.AppError> get activeErrors => (super.noSuchMethod(
        Invocation.getter(#activeErrors),
        returnValue: <_i7.AppError>[],
      ) as List<_i7.AppError>);

  @override
  void showError(_i7.AppError? error) => super.noSuchMethod(
        Invocation.method(
          #showError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showApiError(_i8.ApiError? error) => super.noSuchMethod(
        Invocation.method(
          #showApiError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showValidationError(_i9.ValidationError? error) => super.noSuchMethod(
        Invocation.method(
          #showValidationError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showNetworkError(_i10.NetworkError? error) => super.noSuchMethod(
        Invocation.method(
          #showNetworkError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showClientError(_i11.ClientError? error) => super.noSuchMethod(
        Invocation.method(
          #showClientError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError(String? errorId) => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [errorId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllErrors() => super.noSuchMethod(
        Invocation.method(
          #clearAllErrors,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearErrorsByType(String? errorType) => super.noSuchMethod(
        Invocation.method(
          #clearErrorsByType,
          [errorType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ErrorStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorStore extends _i1.Mock implements _i12.ErrorStore {
  MockErrorStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ObservableList<_i7.AppError> get activeErrors => (super.noSuchMethod(
        Invocation.getter(#activeErrors),
        returnValue: _FakeObservableList_0<_i7.AppError>(
          this,
          Invocation.getter(#activeErrors),
        ),
      ) as _i2.ObservableList<_i7.AppError>);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
      ) as bool);

  @override
  _i13.NetworkQuality get networkQuality => (super.noSuchMethod(
        Invocation.getter(#networkQuality),
        returnValue: _i13.NetworkQuality.excellent,
      ) as _i13.NetworkQuality);

  @override
  bool get isErrorBarVisible => (super.noSuchMethod(
        Invocation.getter(#isErrorBarVisible),
        returnValue: false,
      ) as bool);

  @override
  bool get isErrorBarMinimized => (super.noSuchMethod(
        Invocation.getter(#isErrorBarMinimized),
        returnValue: false,
      ) as bool);

  @override
  bool get showErrorDetailsFlag => (super.noSuchMethod(
        Invocation.getter(#showErrorDetailsFlag),
        returnValue: false,
      ) as bool);

  @override
  bool get autoHideNonCriticalErrors => (super.noSuchMethod(
        Invocation.getter(#autoHideNonCriticalErrors),
        returnValue: false,
      ) as bool);

  @override
  Duration get autoHideDuration => (super.noSuchMethod(
        Invocation.getter(#autoHideDuration),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#autoHideDuration),
        ),
      ) as Duration);

  @override
  bool get showNetworkStatusInBar => (super.noSuchMethod(
        Invocation.getter(#showNetworkStatusInBar),
        returnValue: false,
      ) as bool);

  @override
  bool get hasErrors => (super.noSuchMethod(
        Invocation.getter(#hasErrors),
        returnValue: false,
      ) as bool);

  @override
  bool get hasActiveErrors => (super.noSuchMethod(
        Invocation.getter(#hasActiveErrors),
        returnValue: false,
      ) as bool);

  @override
  int get errorCount => (super.noSuchMethod(
        Invocation.getter(#errorCount),
        returnValue: 0,
      ) as int);

  @override
  bool get shouldShowErrorBar => (super.noSuchMethod(
        Invocation.getter(#shouldShowErrorBar),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldShowOfflineIndicator => (super.noSuchMethod(
        Invocation.getter(#shouldShowOfflineIndicator),
        returnValue: false,
      ) as bool);

  @override
  bool get hasNetworkIssues => (super.noSuchMethod(
        Invocation.getter(#hasNetworkIssues),
        returnValue: false,
      ) as bool);

  @override
  String get errorBarTitle => (super.noSuchMethod(
        Invocation.getter(#errorBarTitle),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#errorBarTitle),
        ),
      ) as String);

  @override
  String get networkStatusText => (super.noSuchMethod(
        Invocation.getter(#networkStatusText),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#networkStatusText),
        ),
      ) as String);

  @override
  bool get canRetryCurrentError => (super.noSuchMethod(
        Invocation.getter(#canRetryCurrentError),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldAutoHideCurrentError => (super.noSuchMethod(
        Invocation.getter(#shouldAutoHideCurrentError),
        returnValue: false,
      ) as bool);

  @override
  set activeErrors(_i2.ObservableList<_i7.AppError>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #activeErrors,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentError(_i7.AppError? value) => super.noSuchMethod(
        Invocation.setter(
          #currentError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isOffline(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isOffline,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set networkQuality(_i13.NetworkQuality? value) => super.noSuchMethod(
        Invocation.setter(
          #networkQuality,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set networkStatus(_i13.NetworkStatus? value) => super.noSuchMethod(
        Invocation.setter(
          #networkStatus,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isErrorBarVisible(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isErrorBarVisible,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isErrorBarMinimized(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isErrorBarMinimized,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showErrorDetailsFlag(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showErrorDetailsFlag,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set autoHideNonCriticalErrors(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #autoHideNonCriticalErrors,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set autoHideDuration(Duration? value) => super.noSuchMethod(
        Invocation.setter(
          #autoHideDuration,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showNetworkStatusInBar(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showNetworkStatusInBar,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_2(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.ReactiveContext);

  @override
  void addError(_i7.AppError? error) => super.noSuchMethod(
        Invocation.method(
          #addError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeError(String? errorId) => super.noSuchMethod(
        Invocation.method(
          #removeError,
          [errorId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllErrors() => super.noSuchMethod(
        Invocation.method(
          #clearAllErrors,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearErrorsByType(String? errorType) => super.noSuchMethod(
        Invocation.method(
          #clearErrorsByType,
          [errorType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showErrorBar() => super.noSuchMethod(
        Invocation.method(
          #showErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hideErrorBar() => super.noSuchMethod(
        Invocation.method(
          #hideErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void minimizeErrorBar() => super.noSuchMethod(
        Invocation.method(
          #minimizeErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void expandErrorBar() => super.noSuchMethod(
        Invocation.method(
          #expandErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleErrorBarMinimized() => super.noSuchMethod(
        Invocation.method(
          #toggleErrorBarMinimized,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showErrorDetails() => super.noSuchMethod(
        Invocation.method(
          #showErrorDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hideErrorDetails() => super.noSuchMethod(
        Invocation.method(
          #hideErrorDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleErrorDetails() => super.noSuchMethod(
        Invocation.method(
          #toggleErrorDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoHideNonCriticalErrors(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAutoHideNonCriticalErrors,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoHideDuration(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #setAutoHideDuration,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowNetworkStatusInBar(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setShowNetworkStatusInBar,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ValidateCustomerFieldsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateCustomerFieldsUseCase extends _i1.Mock
    implements _i3.ValidateCustomerFieldsUseCase {
  MockValidateCustomerFieldsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FieldValidationResult execute(_i15.Customer? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [customer],
        ),
        returnValue: _FakeFieldValidationResult_3(
          this,
          Invocation.method(
            #execute,
            [customer],
          ),
        ),
      ) as _i3.FieldValidationResult);

  @override
  List<String> validateField(
    String? fieldName,
    dynamic value,
    _i15.Customer? customer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateField,
          [
            fieldName,
            value,
            customer,
          ],
        ),
        returnValue: <String>[],
      ) as List<String>);
}

/// A class which mocks [WebSocketPreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketPreferencesRepository extends _i1.Mock
    implements _i16.WebSocketPreferencesRepository {
  MockWebSocketPreferencesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i4.WebSocketPreferences> get preferencesStream =>
      (super.noSuchMethod(
        Invocation.getter(#preferencesStream),
        returnValue: _i6.Stream<_i4.WebSocketPreferences>.empty(),
      ) as _i6.Stream<_i4.WebSocketPreferences>);

  @override
  _i6.Future<_i4.WebSocketPreferences> getPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue: _i6.Future<_i4.WebSocketPreferences>.value(
            _FakeWebSocketPreferences_4(
          this,
          Invocation.method(
            #getPreferences,
            [],
          ),
        )),
      ) as _i6.Future<_i4.WebSocketPreferences>);

  @override
  _i6.Future<void> savePreferences(_i4.WebSocketPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferences,
          [preferences],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i17.WebSocketChannelConfig> getAvailableChannels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableChannels,
          [],
        ),
        returnValue: <_i17.WebSocketChannelConfig>[],
      ) as List<_i17.WebSocketChannelConfig>);

  @override
  _i6.Future<void> setChannelEnabled(
    String? channelId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChannelEnabled,
          [
            channelId,
            enabled,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setChannelPriority(
    String? channelId,
    _i4.NotificationPriority? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChannelPriority,
          [
            channelId,
            priority,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setRealTimeUpdatesEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRealTimeUpdatesEnabled,
          [enabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setConnectionStatusEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConnectionStatusEnabled,
          [enabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  Set<String> getSubscribedChannels() => (super.noSuchMethod(
        Invocation.method(
          #getSubscribedChannels,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  bool shouldShowNotification(
    String? channelId,
    _i4.NotificationPriority? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldShowNotification,
          [
            channelId,
            priority,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
