// Mocks generated by Mockito 5.4.6 from annotations
// in mix_fit/test/integration/network_connectivity_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/error/models/network_status.dart' as _i2;
import 'package:core/error/services/network_monitor.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkStatus_0 extends _i1.SmartFake implements _i2.NetworkStatus {
  _FakeNetworkStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkMonitor extends _i1.Mock implements _i3.NetworkMonitor {
  MockNetworkMonitor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<_i2.NetworkQuality> get qualityStream => (super.noSuchMethod(
        Invocation.getter(#qualityStream),
        returnValue: _i4.Stream<_i2.NetworkQuality>.empty(),
      ) as _i4.Stream<_i2.NetworkQuality>);

  @override
  _i4.Stream<_i2.NetworkStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i4.Stream<_i2.NetworkStatus>.empty(),
      ) as _i4.Stream<_i2.NetworkStatus>);

  @override
  _i2.NetworkStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _FakeNetworkStatus_0(
          this,
          Invocation.getter(#currentStatus),
        ),
      ) as _i2.NetworkStatus);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i2.NetworkQuality get currentQuality => (super.noSuchMethod(
        Invocation.getter(#currentQuality),
        returnValue: _i2.NetworkQuality.excellent,
      ) as _i2.NetworkQuality);

  @override
  void startMonitoring({Duration? interval = const Duration(seconds: 30)}) =>
      super.noSuchMethod(
        Invocation.method(
          #startMonitoring,
          [],
          {#interval: interval},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopMonitoring() => super.noSuchMethod(
        Invocation.method(
          #stopMonitoring,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.NetworkQuality> measureQuality() => (super.noSuchMethod(
        Invocation.method(
          #measureQuality,
          [],
        ),
        returnValue:
            _i4.Future<_i2.NetworkQuality>.value(_i2.NetworkQuality.excellent),
      ) as _i4.Future<_i2.NetworkQuality>);

  @override
  _i4.Future<_i2.NetworkStatus> checkNetworkStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkNetworkStatus,
          [],
        ),
        returnValue: _i4.Future<_i2.NetworkStatus>.value(_FakeNetworkStatus_0(
          this,
          Invocation.method(
            #checkNetworkStatus,
            [],
          ),
        )),
      ) as _i4.Future<_i2.NetworkStatus>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
