// Mocks generated by Mockito 5.4.6 from annotations
// in core/test/error/widgets/error_status_bar_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:core/error/models/app_error.dart' as _i4;
import 'package:core/error/models/network_status.dart' as _i5;
import 'package:core/error/stores/error_store.dart' as _i3;
import 'package:mobx/mobx.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeObservableList_0<T> extends _i1.SmartFake
    implements _i2.ObservableList<T> {
  _FakeObservableList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_2 extends _i1.SmartFake
    implements _i2.ReactiveContext {
  _FakeReactiveContext_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ErrorStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorStore extends _i1.Mock implements _i3.ErrorStore {
  MockErrorStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ObservableList<_i4.AppError> get activeErrors => (super.noSuchMethod(
        Invocation.getter(#activeErrors),
        returnValue: _FakeObservableList_0<_i4.AppError>(
          this,
          Invocation.getter(#activeErrors),
        ),
      ) as _i2.ObservableList<_i4.AppError>);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
      ) as bool);

  @override
  _i5.NetworkQuality get networkQuality => (super.noSuchMethod(
        Invocation.getter(#networkQuality),
        returnValue: _i5.NetworkQuality.excellent,
      ) as _i5.NetworkQuality);

  @override
  bool get isErrorBarVisible => (super.noSuchMethod(
        Invocation.getter(#isErrorBarVisible),
        returnValue: false,
      ) as bool);

  @override
  bool get isErrorBarMinimized => (super.noSuchMethod(
        Invocation.getter(#isErrorBarMinimized),
        returnValue: false,
      ) as bool);

  @override
  bool get showErrorDetailsFlag => (super.noSuchMethod(
        Invocation.getter(#showErrorDetailsFlag),
        returnValue: false,
      ) as bool);

  @override
  bool get autoHideNonCriticalErrors => (super.noSuchMethod(
        Invocation.getter(#autoHideNonCriticalErrors),
        returnValue: false,
      ) as bool);

  @override
  Duration get autoHideDuration => (super.noSuchMethod(
        Invocation.getter(#autoHideDuration),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#autoHideDuration),
        ),
      ) as Duration);

  @override
  bool get showNetworkStatusInBar => (super.noSuchMethod(
        Invocation.getter(#showNetworkStatusInBar),
        returnValue: false,
      ) as bool);

  @override
  bool get hasErrors => (super.noSuchMethod(
        Invocation.getter(#hasErrors),
        returnValue: false,
      ) as bool);

  @override
  bool get hasActiveErrors => (super.noSuchMethod(
        Invocation.getter(#hasActiveErrors),
        returnValue: false,
      ) as bool);

  @override
  int get errorCount => (super.noSuchMethod(
        Invocation.getter(#errorCount),
        returnValue: 0,
      ) as int);

  @override
  bool get shouldShowErrorBar => (super.noSuchMethod(
        Invocation.getter(#shouldShowErrorBar),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldShowOfflineIndicator => (super.noSuchMethod(
        Invocation.getter(#shouldShowOfflineIndicator),
        returnValue: false,
      ) as bool);

  @override
  bool get hasNetworkIssues => (super.noSuchMethod(
        Invocation.getter(#hasNetworkIssues),
        returnValue: false,
      ) as bool);

  @override
  String get errorBarTitle => (super.noSuchMethod(
        Invocation.getter(#errorBarTitle),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#errorBarTitle),
        ),
      ) as String);

  @override
  String get networkStatusText => (super.noSuchMethod(
        Invocation.getter(#networkStatusText),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#networkStatusText),
        ),
      ) as String);

  @override
  bool get canRetryCurrentError => (super.noSuchMethod(
        Invocation.getter(#canRetryCurrentError),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldAutoHideCurrentError => (super.noSuchMethod(
        Invocation.getter(#shouldAutoHideCurrentError),
        returnValue: false,
      ) as bool);

  @override
  set activeErrors(_i2.ObservableList<_i4.AppError>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #activeErrors,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentError(_i4.AppError? value) => super.noSuchMethod(
        Invocation.setter(
          #currentError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isOffline(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isOffline,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set networkQuality(_i5.NetworkQuality? value) => super.noSuchMethod(
        Invocation.setter(
          #networkQuality,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set networkStatus(_i5.NetworkStatus? value) => super.noSuchMethod(
        Invocation.setter(
          #networkStatus,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isErrorBarVisible(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isErrorBarVisible,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isErrorBarMinimized(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isErrorBarMinimized,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showErrorDetailsFlag(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showErrorDetailsFlag,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set autoHideNonCriticalErrors(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #autoHideNonCriticalErrors,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set autoHideDuration(Duration? value) => super.noSuchMethod(
        Invocation.setter(
          #autoHideDuration,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showNetworkStatusInBar(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showNetworkStatusInBar,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_2(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.ReactiveContext);

  @override
  void addError(_i4.AppError? error) => super.noSuchMethod(
        Invocation.method(
          #addError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeError(String? errorId) => super.noSuchMethod(
        Invocation.method(
          #removeError,
          [errorId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllErrors() => super.noSuchMethod(
        Invocation.method(
          #clearAllErrors,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearErrorsByType(String? errorType) => super.noSuchMethod(
        Invocation.method(
          #clearErrorsByType,
          [errorType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showErrorBar() => super.noSuchMethod(
        Invocation.method(
          #showErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hideErrorBar() => super.noSuchMethod(
        Invocation.method(
          #hideErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void minimizeErrorBar() => super.noSuchMethod(
        Invocation.method(
          #minimizeErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void expandErrorBar() => super.noSuchMethod(
        Invocation.method(
          #expandErrorBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleErrorBarMinimized() => super.noSuchMethod(
        Invocation.method(
          #toggleErrorBarMinimized,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showErrorDetails() => super.noSuchMethod(
        Invocation.method(
          #showErrorDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hideErrorDetails() => super.noSuchMethod(
        Invocation.method(
          #hideErrorDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleErrorDetails() => super.noSuchMethod(
        Invocation.method(
          #toggleErrorDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoHideNonCriticalErrors(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAutoHideNonCriticalErrors,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoHideDuration(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #setAutoHideDuration,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowNetworkStatusInBar(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setShowNetworkStatusInBar,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
